import mongoose from "mongoose";
import dotenv from "dotenv";
import Listing from "./models/Listing.js";
import User from "./models/User.js";
import connectDB from "./config/db.js";

dotenv.config();

const seedListings = async () => {
    try {
        await connectDB();

        // Find a user to assign listings to
        // Find a user to assign listings to
        let user = await User.findOne({ email: "demo@example.com" });
        if (!user) {
            user = await User.findOne();
        }

        if (!user) {
            console.log("No user found. Creating a demo user...");
            user = await User.create({
                name: "Demo User",
                email: "demo@example.com",
                password: "password123",
                role: "user",
                profilePicture: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200"
            });
            console.log("Demo user created: demo@example.com / password123");
        } else {
            console.log("Using existing user:", user.email);
            // Do not overwrite profile picture
        }

        const demoListings = [
            // Roommate listings
            {
                user: user._id,
                title: "Looking for Roommate in Whitefield",
                type: "Roommate",
                description: "3BHK shared with professionals. Looking for one more roommate. Fully furnished.",
                price: 7500,
                location: "Whitefield, Bangalore",
                amenities: ["WiFi", "AC", "Parking", "Furnished"],
                images: ["https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543220",
                latitude: 12.9698,
                longitude: 77.7499,
            },
            {
                user: user._id,
                title: "Female Roommate Needed - Powai",
                type: "Roommate",
                description: "2BHK apartment near IIT Powai. Looking for female roommate. Good connectivity.",
                price: 8000,
                location: "Powai, Mumbai",
                amenities: ["WiFi", "Gym", "Security", "Power Backup"],
                images: ["https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543221",
                latitude: 19.1197,
                longitude: 72.9078,
            },
            {
                user: user._id,
                title: "Roommate Wanted - Indiranagar",
                type: "Roommate",
                description: "Looking for a chill roommate to share 2BHK. Near pubs and cafes.",
                price: 8500,
                location: "Indiranagar, Bangalore",
                amenities: ["WiFi", "AC", "Balcony", "Furnished"],
                images: ["https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543240",
                latitude: 12.9716,
                longitude: 77.5946,
            },
            {
                user: user._id,
                title: "Working Professional Roommate - Noida",
                type: "Roommate",
                description: "3BHK near Sector 62 metro. Looking for one working professional roommate.",
                price: 7000,
                location: "Sector 62, Noida",
                amenities: ["WiFi", "Parking", "Security", "Lift"],
                images: ["https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543241",
                latitude: 28.6270,
                longitude: 77.3771,
            },

            // Coliving listings
            {
                user: user._id,
                title: "Modern Coliving Space HSR Layout",
                type: "Coliving",
                description: "Premium coliving with private rooms, common lounge, and workspace. Perfect for young professionals.",
                price: 9500,
                location: "HSR Layout, Bangalore",
                amenities: ["WiFi", "AC", "Gym", "Coworking", "Laundry"],
                images: ["https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543222",
                latitude: 12.9082,
                longitude: 77.6476,
            },
            {
                user: user._id,
                title: "Coliving Community - Gurgaon",
                type: "Coliving",
                description: "Vibrant coliving community with events, networking, and modern amenities.",
                price: 9000,
                location: "Sector 29, Gurgaon",
                amenities: ["WiFi", "AC", "Pool", "Events", "Housekeeping"],
                images: ["https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543223",
                latitude: 28.4595,
                longitude: 77.0266,
            },
            {
                user: user._id,
                title: "Urban Coliving - Bandra",
                type: "Coliving",
                description: "Trendy coliving space with rooftop terrace. Close to Bandra station.",
                price: 9800,
                location: "Bandra West, Mumbai",
                amenities: ["WiFi", "AC", "Rooftop", "Coworking", "Events"],
                images: ["https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543242",
                latitude: 19.0596,
                longitude: 72.8295,
            },
            {
                user: user._id,
                title: "Coliving Hub - Hitech City",
                type: "Coliving",
                description: "Tech-friendly coliving near IT companies. High-speed WiFi and workstations.",
                price: 8500,
                location: "Hitech City, Hyderabad",
                amenities: ["WiFi", "AC", "Coworking", "Gym", "Parking"],
                images: ["https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543243",
                latitude: 17.4435,
                longitude: 78.3772,
            },

            // PG (Paying Guest) listings
            {
                user: user._id,
                title: "PG for Students in North Campus",
                type: "PG",
                description: "Twin sharing PG with food. Walking distance from DU colleges.",
                price: 4500,
                location: "Kamla Nagar, Delhi",
                amenities: ["WiFi", "Food", "Laundry"],
                images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543215",
                latitude: 28.6812,
                longitude: 77.2065,
            },
            {
                user: user._id,
                title: "Girls PG Near Electronic City",
                type: "PG",
                description: "Safe and secure PG for working women with food and housekeeping.",
                price: 6000,
                location: "Electronic City, Bangalore",
                amenities: ["WiFi", "Food", "Security", "Laundry"],
                images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543224",
                latitude: 12.8456,
                longitude: 77.6603,
            },
            {
                user: user._id,
                title: "Premium PG for IT Professionals",
                type: "PG",
                description: "AC rooms with attached bathroom. Food included. Near Hinjewadi IT Park.",
                price: 7000,
                location: "Hinjewadi, Pune",
                amenities: ["WiFi", "AC", "Food", "Parking"],
                images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543225",
                latitude: 18.5912,
                longitude: 73.7396,
            },

            // Flatmate listings
            {
                user: user._id,
                title: "Flatmate Required - Malad West",
                type: "Flatmate",
                description: "2BHK flat sharing. Looking for working professional as flatmate.",
                price: 7800,
                location: "Malad West, Mumbai",
                amenities: ["WiFi", "Lift", "Parking", "Security"],
                images: ["https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543226",
                latitude: 19.1865,
                longitude: 72.8356,
            },
            {
                user: user._id,
                title: "Searching Flatmate in Koramangala",
                type: "Flatmate",
                description: "Spacious 3BHK looking for one more flatmate. Gym and pool available.",
                price: 8200,
                location: "Koramangala, Bangalore",
                amenities: ["WiFi", "Gym", "Pool", "Security"],
                images: ["https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543227",
                latitude: 12.9352,
                longitude: 77.6245,
            },

            // Room listings
            {
                user: user._id,
                title: "Single Room Available - Bandra",
                type: "Room",
                description: "Private room in shared apartment. Quiet neighborhood, close to station.",
                price: 6500,
                location: "Bandra East, Mumbai",
                amenities: ["WiFi", "AC", "Attached Bathroom"],
                images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543228",
                latitude: 19.0596,
                longitude: 72.8295,
            },
            {
                user: user._id,
                title: "Furnished Room in JP Nagar",
                type: "Room",
                description: "Well-furnished single occupancy room with all amenities nearby.",
                price: 5500,
                location: "JP Nagar, Bangalore",
                amenities: ["WiFi", "Furnished", "Power Backup"],
                images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543229",
                latitude: 12.9077,
                longitude: 77.5859,
            },
            {
                user: user._id,
                title: "Spacious Room - Salt Lake",
                type: "Room",
                description: "Large room with balcony. Great for students and young professionals.",
                price: 4800,
                location: "Salt Lake, Kolkata",
                amenities: ["WiFi", "Balcony", "Security"],
                images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543230",
                latitude: 22.5838,
                longitude: 88.4317,
            },

            // Entire House listings
            {
                user: user._id,
                title: "Modern 3BHK House in South Delhi",
                type: "Entire House",
                description: "Spacious 3BHK with servant quarter. Located in a posh colony.",
                price: 9800,
                location: "Greater Kailash, Delhi",
                amenities: ["WiFi", "AC", "Parking", "Garden"],
                images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36f89?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543214",
                latitude: 28.5562,
                longitude: 77.2410,
            },
            {
                user: user._id,
                title: "Luxury Villa in Jubilee Hills",
                type: "Entire House",
                description: "Standalone 4BHK villa with garden and modern interiors.",
                price: 10000,
                location: "Jubilee Hills, Hyderabad",
                amenities: ["WiFi", "AC", "Parking", "Garden", "Security"],
                images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543231",
                latitude: 17.4239,
                longitude: 78.4130,
            },
            {
                user: user._id,
                title: "Independent House - Anna Nagar",
                type: "Entire House",
                description: "Well-maintained 2BHK independent house. Family-friendly neighborhood.",
                price: 8500,
                location: "Anna Nagar, Chennai",
                amenities: ["WiFi", "Parking", "Water Supply", "Security"],
                images: ["https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543232",
                latitude: 13.0878,
                longitude: 80.2086,
            },
            {
                user: user._id,
                title: "Duplex House - Dwarka",
                type: "Entire House",
                description: "Spacious duplex house with garden. Perfect for families.",
                price: 9200,
                location: "Dwarka Sector 10, Delhi",
                amenities: ["WiFi", "AC", "Garden", "Parking", "Security"],
                images: ["https://images.unsplash.com/photo-1600596542815-22b5c1275efb?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543244",
                latitude: 28.5921,
                longitude: 77.0460,
            },
            {
                user: user._id,
                title: "Standalone Villa - Bellandur",
                type: "Entire House",
                description: "Modern 3BHK villa with private parking. Gated community.",
                price: 10000,
                location: "Bellandur, Bangalore",
                amenities: ["WiFi", "AC", "Gym", "Pool", "Security"],
                images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543245",
                latitude: 12.9266,
                longitude: 77.6733,
            },

            // More PG listings
            {
                user: user._id,
                title: "Boys PG - Viman Nagar",
                type: "PG",
                description: "Clean PG with food for working professionals. Near airport.",
                price: 5500,
                location: "Viman Nagar, Pune",
                amenities: ["WiFi", "Food", "Laundry", "AC"],
                images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543246",
                latitude: 18.5679,
                longitude: 73.9143,
            },
            {
                user: user._id,
                title: "Executive PG - Salt Lake",
                type: "PG",
                description: "Premium PG for IT professionals with all amenities.",
                price: 6500,
                location: "Salt Lake Sector 5, Kolkata",
                amenities: ["WiFi", "AC", "Food", "Housekeeping"],
                images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543247",
                latitude: 22.5726,
                longitude: 88.4319,
            },

            // More Flatmate listings
            {
                user: user._id,
                title: "Need Flatmate - Jayanagar",
                type: "Flatmate",
                description: "2BHK in peaceful locality. Looking for vegetarian flatmate.",
                price: 7500,
                location: "Jayanagar 4th Block, Bangalore",
                amenities: ["WiFi", "Parking", "Security", "Power Backup"],
                images: ["https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543248",
                latitude: 12.9250,
                longitude: 77.5937,
            },
            {
                user: user._id,
                title: "Flatmate Wanted - Model Town",
                type: "Flatmate",
                description: "3BHK furnished flat. Looking for one more flatmate.",
                price: 6800,
                location: "Model Town, Delhi",
                amenities: ["WiFi", "AC", "Furnished", "Parking"],
                images: ["https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543249",
                latitude: 28.7041,
                longitude: 77.1952,
            },

            // More Room listings
            {
                user: user._id,
                title: "Private Room - Connaught Place",
                type: "Room",
                description: "Single room in heart of Delhi. Great for working professionals.",
                price: 9500,
                location: "Connaught Place, Delhi",
                amenities: ["WiFi", "AC", "Attached Bathroom", "Furnished"],
                images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543250",
                latitude: 28.6315,
                longitude: 77.2167,
            },
            {
                user: user._id,
                title: "Cozy Room - MG Road",
                type: "Room",
                description: "Comfortable single room on MG Road. Metro connectivity.",
                price: 8000,
                location: "MG Road, Bangalore",
                amenities: ["WiFi", "AC", "Furnished", "Metro Access"],
                images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543251",
                latitude: 12.9759,
                longitude: 77.6061,
            },
            {
                user: user._id,
                title: "Single Room - Thane West",
                type: "Room",
                description: "Affordable room with all basic amenities. Near station.",
                price: 5200,
                location: "Thane West, Mumbai",
                amenities: ["WiFi", "Furnished", "Security"],
                images: ["https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543252",
                latitude: 19.2183,
                longitude: 72.9781,
            },

            // Legacy listings (keeping a few with updated types)
            {
                user: user._id,
                title: "Cozy 1BHK in Indiranagar",
                type: "Room",
                description: "A beautiful 1BHK apartment in the heart of Indiranagar. Close to metro and restaurants.",
                price: 8500,
                location: "Indiranagar, Bangalore",
                amenities: ["WiFi", "AC", "Parking", "Geyser"],
                images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543210",
                latitude: 12.9716,
                longitude: 77.5946,
            },
            {
                user: user._id,
                title: "Spacious 2BHK in Koramangala",
                type: "Flatmate",
                description: "Fully furnished 2BHK with balcony. Ideal for families or bachelors.",
                price: 9500,
                location: "Koramangala, Bangalore",
                amenities: ["WiFi", "Gym", "Pool", "Security"],
                images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543211",
                latitude: 12.9352,
                longitude: 77.6245,
            },
            {
                user: user._id,
                title: "Sea View Flat in Bandra",
                type: "Entire House",
                description: "Luxury flat with stunning sea view. Premium amenities included.",
                price: 10000,
                location: "Bandra West, Mumbai",
                amenities: ["WiFi", "AC", "Sea View", "Concierge"],
                images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543212",
                latitude: 19.0596,
                longitude: 72.8295,
            },
            {
                user: user._id,
                title: "Compact Studio in Andheri",
                type: "Room",
                description: "Affordable studio apartment near Andheri station. Good connectivity.",
                price: 6500,
                location: "Andheri East, Mumbai",
                amenities: ["WiFi", "Lift", "Security"],
                images: ["https://images.unsplash.com/photo-1598928506312-6e025fe1c0a0?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543213",
                latitude: 19.1136,
                longitude: 72.8697,
            },
            {
                user: user._id,
                title: "2BHK Apartment in Adyar",
                type: "Flatmate",
                description: "Well ventilated 2BHK apartment. Close to beach and temples.",
                price: 7200,
                location: "Adyar, Chennai",
                amenities: ["WiFi", "Parking", "Water Supply"],
                images: ["https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543216",
                latitude: 13.0012,
                longitude: 80.2565,
            },
            {
                user: user._id,
                title: "IT Corridor Flat in OMR",
                type: "Coliving",
                description: "Furnished flat suitable for IT professionals. Near Tidel Park.",
                price: 8800,
                location: "Thoraipakkam, Chennai",
                amenities: ["WiFi", "AC", "Gym", "Power Backup"],
                images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543217",
                latitude: 12.9249,
                longitude: 80.2312,
            },

            // Lucknow Specific Listings (Price 2000-6000)
            {
                user: user._id,
                title: "Student Room in Gomti Nagar",
                type: "Room",
                description: "Affordable single room near BBD University. Perfect for students.",
                price: 3500,
                location: "Gomti Nagar, Lucknow",
                amenities: ["WiFi", "Fan", "Bed", "Study Table"],
                images: ["https://images.unsplash.com/photo-1598928506312-6e025fe1c0a0?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543250",
                latitude: 26.8467,
                longitude: 80.9462,
            },
            {
                user: user._id,
                title: "Budget Friendly PG",
                type: "PG",
                description: "Double sharing PG with food included. Near Kapoorthala.",
                price: 5500,
                location: "Aliganj, Lucknow",
                amenities: ["Food", "WiFi", "Cleaning", "Geyser"],
                images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543251",
                latitude: 26.8856,
                longitude: 80.9450,
            },
            {
                user: user._id,
                title: "Coliving Space - Indira Nagar",
                type: "Coliving",
                description: "Modern co-living space with shared lounge and kitchen.",
                price: 6000,
                location: "Indira Nagar, Lucknow",
                amenities: ["WiFi", "Power Backup", "Gaming Zone", "Kitchen"],
                images: ["https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543252",
                latitude: 26.8816,
                longitude: 80.9930,
            },
            {
                user: user._id,
                title: "Need Flatmate - Hazratganj",
                type: "Flatmate",
                description: "Looking for a chill flatmate to share a 2BHK. Old charm building.",
                price: 4500,
                location: "Hazratganj, Lucknow",
                amenities: ["Furnished", "Microwave", "Fridge", "WiFi"],
                images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543253",
                latitude: 26.8467,
                longitude: 80.9462,
            },
            {
                user: user._id,
                title: "Small 1RK for Rent",
                type: "Entire House",
                description: "Independent 1 room kitchen set. Ground floor.",
                price: 4000,
                location: "Rajajipuram, Lucknow",
                amenities: ["Water Supply", "Parking", "Pet Friendly"],
                images: ["https://images.unsplash.com/photo-1484154218962-a1c00207099b?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543254",
                latitude: 26.8393,
                longitude: 80.8956,
            },
            {
                user: user._id,
                title: "Shared Room for Girls",
                type: "Roommate",
                description: "Looking for a female roommate for a managed apartment.",
                price: 2500,
                location: "Charbagh, Lucknow",
                amenities: ["Security", "CCTV", "WiFi"],
                images: ["https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543255",
                latitude: 26.8318,
                longitude: 80.9160,
            },
            {
                user: user._id,
                title: "Student PG for Boys",
                type: "PG",
                description: "Triple sharing room for engineering students. Walking distance to colleges.",
                price: 3000,
                location: "Faizabad Road, Lucknow",
                amenities: ["WiFi", "Mess", "Laundry"],
                images: ["https://images.unsplash.com/photo-1596276020587-8044fe049813?auto=format&fit=crop&q=80&w=800"],
                contactPhone: "9876543256",
                latitude: 26.8745,
                longitude: 81.0150,
            },
        ];

        await Listing.insertMany(demoListings);
        console.log("Demo listings added successfully!");
        process.exit();
    } catch (error) {
        console.error("Error seeding listings:", error);
        process.exit(1);
    }
};

seedListings();
